version: '3.7'

services:
  anonymize-cef:
    image: translatednet/anonymize-cef:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
            - node.labels.zone == dc
      labels:
        - traefik.enable=true
        - traefik.http.routers.anonymize-cef.service=clean-cef
        - traefik.http.routers.anonymize-cef.entryPoints=web
        - traefik.http.routers.anonymize-cef.rule=Host(`cef-datamarketplace-tmanonymizer.translated.com`)
        - traefik.http.services.anonymize-cef.loadBalancer.server.port=8081
        - traefik.http.services.anonymize-cef.loadBalancer.passHostHeader=true
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 60s
      resources:
        limits:
          cpus: '2'
          memory: 2G
networks:
  traefik:
    external: true
